version: "3.9"

services:
  db:
    image: postgres:16
    container_name: flights_db
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: